[project]
name = "aforisms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awscli>=1.42.66",
    "boto3>=1.40.66",
    "nltk>=3.9.2",
    "ydb>=3.21.13",
]
